name: update flake-lock

permissions:
  contents: write

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '30 2 * * *' # runs daily at 02:30AM

jobs:
  lockfile:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Update flake.lock
        run: |
          nix flake update

      - name: Push commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot
          commit_author: Flake Bot <actions@github.com>
          skip_dirty_check: false
          skip_fetch: true
