background = "#1e1e2eff"
blend = true
blocks_overlap = 0.0
blocks_r = 6
color = "#cba6f7ff"
command = "i3status-rs"
font = "Comic Shanns Mono 12"
height = 20
hide_inactive_tags = true
invert_touchpad_scrolling = true
margin_bottom = 0
margin_left = 8
margin_right = 8
margin_top = 4
position = "top"
#separator = "#9a8a62ff"
separator_width = 0
show_layout_name = false
tag_bg = "#181825ff"
tag_fg = "#a6adc8ff"
tag_focused_bg = "#b4befeff"
tag_focused_fg = "#282828ff"
tag_inactive_bg = "#282828ff"
tag_inactive_fg = "#d79921ff"
tag_urgent_bg = "#dc8a78ff"
tag_urgent_fg = "#282828ff"
tags_padding = 15.0
tags_r = 6

[wm.river]
max_tag = 9
