[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 60

[icons]
icons = "awesome6"

[theme]
theme = "ctp-mocha"
